spring.application.name=bistral-auth-service
spring.config.import=configserver:http://localhost:8888
server.port = 8086
jwt.private.key.path=classpath:keys/private.pem
jwt.public.key.path=classpath:keys/public.pem